### ISSUE TITLE
Spells, and Input

### ISSUE THREAD

**Issue by ajusa** [Ajusa/Spell#20]
Client starts typing in spell, client starts recording key presses, if a spell is found with those key presses, it is fired. If no spell found, do nothing. If no mana, do nothing. Also, add general regen to full mana over time, with a variable called max mana. When you kill someone, you add a number based on their max mana to your max mana (eg 1/4).

**Comment by mittsq** [comment]
~~What keys would the spells be assigned to?~~

Nevermind, I'll use U I O and P.
