### ISSUE TITLE
Commit timed player code

### ISSUE THREAD

**Issue by mittsq** [Ajusa/Spell#23]
Be sure to pull before hand, again.

**Comment by ajusa** [comment]
Timed player code? What is that?

**Comment by mittsq** [comment]
Remember? The one where we tried to make the players update and 20 ticks per second? If you don't want to implement that, it's fine. I was just wondering because your code would get overwritten by other changes.

**Comment by ajusa** [comment]
I am leaving that out for now, as the server is being rewritten, so I will be thinking up a new way to send and receive data. Also, I did make some headway into the server, and it isn't too difficult.

**Comment by mittsq** [comment]
Ok sounds good.
