### ISSUE TITLE
Player Server Performance

### ISSUE THREAD

**Issue by ajusa** [Ajusa/Spell#28]
Do we want to have the client receive the entire player array 20 times a second, or just the changes? When they disconnect, or when they connect, they can receive the entire array.

**Comment by mittsq** [comment]
If possible, I think just the changes would be good, especially for performance.

**Comment by ajusa** [comment]
Changes would be easier, which I have already implemented. The entire Player array was what we had written down before you left, so just wanted to make sure. Closing this issue.
