### ISSUE TITLE
Combos

### ISSUE THREAD

**Issue by ajusa** [Ajusa/Spell#31]
Whenever someone pushes the keys corresponding to each element, we should display a pixel art format of the element. Like a little fire icon for the key it corresponds to.

**Comment by mittsq** [comment]
I can draw the icons for each element. We can use them in multiple places, too.

**Comment by ajusa** [comment]
Exactly. I was thinking, for the combos, and above each person's head. I suggest using avatar's symbols, but pixel art them.

**Comment by ajusa** [comment]
I will work on this over the weekend, but my priority is to do the server first.

**Comment by ajusa** [comment]
Nice job, @epicmittmitt !
If you think it is done, then go ahead and close the issue :D

**Comment by mittsq** [comment]
Implemented in b1baed6d. Closed.
