### ISSUE TITLE
Gameplay

### ISSUE THREAD

**Issue by ajusa** [Ajusa/Spell#32]
This is going to be a large post, describing the game play. Large amounts of it will be copied into the "index.html".

This game saves to local storage every few seconds, and on every kill. That way, you do not lose all of your progress.

You are living in a closed world, with one "box" per every 5 or 10 levels. Other boxes are restricted to you unless you are of that level. Each box has some terrain, platforms, spikes, etc. These will most likely be hard coded. The background of each box will be a different color to signify the level.

Spells will be automatically cast when you type in the combo. NOT when you hit the "s" key. This is to keep fast paced gameplay, and make it easier to battle. Certain spells will be locked until a level is reached. Second order spells (any type of combo) will be unlocked one by one. Spells will have different speeds, and certain ones can have knockback. Poison may be added in the future.

The player. Each player will have the current stats they currently have, in addition to a level, an element, and total xp. The element is determined by which key has been pressed the most. If one has pushed the fire key the most, the player's element becomes fire, so they become weaker to water. This leads to several playing styles, so you could try and be balanced, or you could go all in with an element. This also means that spells cast with the opposite element will be weaker. Eg, fire type player will weak water spells.

Skill points. Every time a person levels up, they will gain a fixed number of skill points (2). These skill points can be used to increase overall damage, defense, speed, and decrease the amount of mana used per spell. The skill points will be changed by using either the number keys, or some other keys available to the player. Each skill point will change it's property by one percent.

Levels will be counted as log(x0, so it will take more xp to level up lvl 100 than lvl 1. XP increases when you kill someone, or when you run over an xp orb. Each box will have different xp orbs, giving more or less xp. (XP orbs are a good idea in case there is nobody on).

Feedback will be appreciated.

**Comment by ajusa** [comment]
One big area which I am unsure about is how/when to unlock spells. Should you only be able to unlock spells of your type? Should only balanced people be able to unlock all spells? I need a gamemaster or something to help me.

**Comment by ajusa** [comment]
_cough_ @DarkP1ant

**Comment by mittsq** [comment]
Not sure who @DarkP1ant is, but I can take care of some of these things.

Levels/XP are complete, although there appears to be a step curve when going from levels 3 to 4 to 5. We can adjust the formulas if necessary. 

I can implement skill points, this shouldn't be too difficult. Same thing with element bias, but that will probably take more time.

**Comment by ajusa** [comment]
Okay. Dark Plant is Noah. He kinda agreed to help. Skill points are pretty easy...
Element bias is harder. If you can do them, go for it. Keep them in the Player class.
