### ISSUE TITLE
Skill Points

### ISSUE THREAD

**Issue by ajusa** [Ajusa/Spell#44]
I don't really know how this should be implemented...
Should there be a gui? Or more buttons?

**Comment by mittsq** [comment]
There will be buttons that can be activated by click or number key press. They can change Max HP, Max Mana, and Passive Experience Rate. If I need to add anything else, let me know.

Also, @AlphaBetaR I'll need texture files for the skill buttons, in 64x resolution preferably. I will make placeholder ones for now, so they can be low-priority.
