### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by mittsq** [Ajusa/Spell#45]
When the framerate decreases, the entire game's speed decreases. So all movement, spells, etc. move slower depending on the FPS (30 fps makes game run at 1/2 speed).

This is obviously not intentional .. is there some kind of frame skip we can implement if the frame rate dips to avoid engine slowdown?

**Comment by ajusa** [comment]
Good point.
What I have been thinking about, is that we rewrite some of the code to be separated into logic and rendering components. The logic runs at a consistent 30 times or 20 times a second, while the frames run the way they currently do. This also leads to better multiplayer performance

**Comment by ajusa** [comment]
This is basically the animation issue, so I am closing this
