### ISSUE TITLE
Experience Meter

### ISSUE THREAD

**Issue by mittsq** [Ajusa/Spell#81]
Someone broke the Exp bar's update sequence in a recent commit, and I'm tearing my hair out trying to find the problem. Note that the other bars update just fine.

These two commits f320720 and 10cd35f are the culprit. `app.js`'s blame says @Ajusa committed both of those; see `app.js:62-3;67`.

Other than that, no one touched the bar updater, so I'm confused. Pls help thx.

**Comment by ajusa** [comment]
Oops.

**Comment by ajusa** [comment]
Fixed now. Closing
